Added precision option to round floating point values.
andreyvit/json-diff pull request #74
Opened 2022-03-05 02:57 UTC by Digicrat

IEEE 754 floating point numbers are not always precise, and rounding errors can accumulate when round-tripping data making comparisons difficult.  This is particularly common on certain platforms, such as cJSON, where conversions between float and double can aggravate matters.  

This change introduces a "--precision" option that will explicitly round all floating point numbers in the JSON file to the specified precision prior to comparison.

2022-03-05 15:43 UTC, ewoudenberg requested changes
Thank you for your submission! If you can address the comments and adjust the unit tests so that:

1. All existing tests pass
2. There are new test(s) for the precision feature.

I will be happy to merge your change.

2022-03-05 15:43 UTC, ewoudenberg commented on lib/cli.js
> +      '  -p, --precision PREC    Round all floating point numbers to this precision prior to comparison'
How about 
```
' -p, --precision PREC Round all floating point numbers to this number of decimal places prior to comparison'
```

2022-03-05 15:43 UTC, ewoudenberg commented on lib/cli.js
> +  if (options.precision) {
How about:
```
if (options.precision != undefined) {
```
In this way, a precision of 0 can be specified.

2022-03-05 23:07 UTC, Digicrat commented
I fixed the existing test and made the suggested changes.

I wasn't able to add a new unit test though, as the way the existing tests are written the new logic in cli.js isn't invoked.

2022-03-06 18:06 UTC, ewoudenberg commented
Thank you! I've altered the PR slightly and merged it.
https://github.com/andreyvit/json-diff/pull/75

2022-03-06 18:06 UTC, closed without merging